### GET /
GET http://localhost:5000

### POST
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "ankhaa@gmail.com",
    "password": "123ankhaa123"
}

### POST
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "ankhaa@gmail.com",
    "password": "123ankhaa123"
}